namespace GoogleMapsServices
{
    public enum AddressType
    {
        unknown,
        street_address,
        route,
        intersection,
        political,
        country,
        administrative_area_level_1,
        administrative_area_level_2,
        administrative_area_level_3,
        colloquial_area,
        locality,
        sublocality,
        neighborhood,
        premise,
        subpremise,
        postal_code,
        natural_feature,
        airport,
        park,
        bus_station,
        transit_station,
        point_of_interest,
        post_box,
        street_number,
        floor,
        room,
        establishment
    }
}